writeln("Is 0 true?")
writeln(0 == true)
writeln("Is 0 false?")
writeln(0 == false)
writeln("0 is a different type. So it is not true neither false")
writeln("Is empty string nil, true or false?")
writeln("Is empty string nil?")
writeln("" == nil)
writeln("Is empty string true?")
writeln("" == true)
writeln("Is empty string false?")
writeln("" == false)
writeln("empty string is different type. So it is not nil, neither true, neither false")